### ISSUE TITLE
Why ONBUILD?

### ISSUE THREAD

**Issue by bkeroackdsc** [dollarshaveclub/fastboot-docker#1]
@pwfisher I'm curious why you chose to implement the base image using ``ONBUILD``. While not incorrect per se, it is inconsistent with our other base images which bundle scripts for downstream images to use.

``ONBUILD`` seems a little magical to me, as opposed to including `/opt/scripts/build.sh` which the downstream Dockerfile executes.

Thoughts?

**Comment by pwfisher** [comment]
What feels "magical" to me is control flow which I cannot easily reconstruct and follow. In this solution, all the Docker build logic is contained in one place and is as simple as possible.

Without ONBUILD, the downstream image has to know implementation details of the upstream image.

The current downstream repo needs to know about
* .dockerignore contents
* quay.io/dollarshaveclub/emberapp-base:master
* $NPM_CACHE
* $SCRIPT_DIR
* $REPONAME
* $PREBUILD_ENVS
* prebuild.sh
* git-version.sh
* post-build.sh

Then there are the additional (unused?) dependencies you can find if you dig further:
* $EMBERAPP_ENVIRONMENT
* $SKIP_EMBER_BUILD
* $PREBUILT_APP_ENV
* $BOWER_INSTALL
* $TARGET_PATH
* $LISTEN_PORT

If you go another step upstream, you find:
* $NGINX_WORKERS
* $NGINX_MULTI_ACCEPT
* $NGINX_WORKER_CONNECTIONS
* $NGINX_NO_DEFAULT_GZIP
* $PASSENGER_MAX_POOL_SIZE
* $PASSENGER_MIN_INSTANCES
* $PASSENGER_MAX_INSTANCES
* $PASSENGER_ROLLING_RESTARTS
* $PASSENGER_USER
* $PASSENGER_RESIST_DEPLOYMENT_ERRORS
* $PASSENGER_START_TIMEOUT
* $PASSENGER_FRIENDLY_ERROR_PAGES
* $PASSENGER_START_URL

All these environment variables could be set at any point in the five levels of nested Dockerfiles (dsc/my-app > dsc/ember > dsc/passenger > passenger-nodejs > phusion/baseimage > ubuntu). In fact, many are used at runtime, so you can't really know how this container will behave without also knowing the runtime environment. It makes my head spin.

When you include things like the passenger init system and config templating it is a huge challenge to understand exactly what is going on in our existing build. It took me a long, long time to wrap my head around it all. I had to read a ton of documentation and actually go to the source of passenger (then its parent, then its parent).

Most importantly, you can't look at our existing upstream repo and see how it works. Critical implementation details are only found in the downstream image. And then others are upstream. And upstream from that. And upstream from that. There are all kinds of interdependencies between different layers in the stack.

In my solution, the downstream image needs to know:
* .dockerignore contents
* dollarshaveclub/fastboot
* github-ssh/id_rsa

And these 3 things are in the README.

The developer who wants to understand the build process needs to look in one place: here.

I was desperately yearning for something simpler. This definitely scratches my itch. YMMV?

**Comment by pwfisher** [comment]
Did you get the "add a script, then run it" pattern from Phusion? E.g., https://github.com/phusion/baseimage-docker/blob/master/image/Dockerfile. I do not think their Docker work is something to emulate. (Not a big fan of Passenger, either, TBH.)

I read a lot of other peoples' Dockerfiles and lots of articles on best practices and feel good about the end result here. I canvassed community practice using github search with `language:Dockerfile` for more ideas.

For example, where to `COPY` things? Many just use the root. I put everything in `/app` because I want my code together (as opposed to `/dist` and `/server`) but not more deeply nested (e.g. `/opt/src/app/dist`) because I own this filesystem and it is minimal. It is so short that replacing it with a variable just makes the code noisier. The hardcoding of paths is a feature. It delivers simplicity.

**Comment by bkeroackdsc** [comment]
What if the fastboot app has no need for a private github key? In this implementation downstream would have to provide a fake one just to get the image to build.

**Comment by pwfisher** [comment]
I provide a fake github key by default, so it works out of the box.
